### ISSUE TITLE
Buy Links not working

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/inkwellmanagement#1]
> The amazon and indiebound links on our website don’t seem to be working consistently.  
> Could someone take a look?
> For this title, for ex, amazon is ok but indiebound isn’t: http://inkwellmanagement.com/books/we-fed-an-island

> for this title, neither work (but b&n is ok) 
http://inkwellmanagement.com/books/chasing-my-cure

 The Indibound just need to be changed from booksense to indiebound.com

**Comment by AdamChlan** [comment]
Indiebound issue is fixed and Isbn 10 info shared with Jenny, so she can add in for the books missing it. Closing this out.
